# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd8951e36e9e898d4a6fe09847b001199fb77e114b9f9fee1bdbfd9c1baf2e1f9fe5f447bb9e82abbc44f3c2e9669d78e37dc7e58c4a918d09a56d4f76dc069f

test:
  secret_key_base: 919a52fcd94ef064b962c598370046113bdd366111f4d242ac0dc8cb5638139151791dac2ca6ec22fc907f3af63460a6a6cabcf4b3cfe03c40b5ee78f43999da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
